for l = 1:length(data.z_offsets)
    cbh(l) = uicontrol('Style', 'checkbox', 'Parent', controls.hfrm, ... 
        'Units', 'normalized', 'String', handles.label(l),  ...
        'Position', [0.4, 0.5 + length(data.z_offsets)/2 * chk_height, ...
        chk_width, chk_height],...
        'String', '', ...
        'Enable', 'off');
    
end

for r = 1:length(data.z_offsets)
    cbh(l) = uicontrol('Style', 'checkbox', 'Parent', controls.hfrm, ... 
        'Units', 'normalized', 'String', handles.label(l),  ...
        'Position', [0.6, 0.5 + length(data.z_offsets)/2 * chk_height, ...
        chk_width, chk_height],...
        'String', '', ...
        'Enable', 'off');
    
end